
package ec.gob.ambiente.suia.web.services.financial.financialws.controller;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import ec.gob.ambiente.util.Constant;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
//@WebServiceClient(name = "PaymentServiceInternal", targetNamespace = "http://controller.financialWS.financial.services.web.suia.ambiente.gob.ec/", wsdlLocation = "http://mapainteractivo.ambiente.gob.ec:8223/financialWS/PaymentServiceInternal/PaymentServiceInternal?wsdl")
@WebServiceClient(name = "PaymentServiceInternal", targetNamespace = "http://controller.financialWS.financial.services.web.suia.ambiente.gob.ec/", wsdlLocation = "http://qa-suia.ambiente.gob.ec:8092/financialWS/PaymentServiceInternal/PaymentServiceInternal?wsdl")
public class PaymentServiceInternal_Service
    extends Service
{

    private final static URL PAYMENTSERVICEINTERNAL_WSDL_LOCATION;
    private final static WebServiceException PAYMENTSERVICEINTERNAL_EXCEPTION;
    private final static QName PAYMENTSERVICEINTERNAL_QNAME = new QName("http://controller.financialWS.financial.services.web.suia.ambiente.gob.ec/", "PaymentServiceInternal");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(Constant.getServicePayAddres());
            //url = new URL("http://qa-suia.ambiente.gob.ec:8092/financialWS/PaymentServiceInternal/PaymentServiceInternal?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAYMENTSERVICEINTERNAL_WSDL_LOCATION = url;
        PAYMENTSERVICEINTERNAL_EXCEPTION = e;
    }

    public static URL getServiceUrl() throws MalformedURLException {
		return new URL(Constant.getServicePayAddres());
		/*URL x= new URL(Constant.getServicePayAddres());
		//return new URL("http://qa-suia.ambiente.gob.ec:8092/financialWS/PaymentServiceInternal/PaymentServiceInternal?wsdl");
		return x;*/
	}
     
    public PaymentServiceInternal_Service() throws MalformedURLException {
        super(getServiceUrl(), PAYMENTSERVICEINTERNAL_QNAME);
    }

    public PaymentServiceInternal_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAYMENTSERVICEINTERNAL_QNAME, features);
    }

    public PaymentServiceInternal_Service(URL wsdlLocation) {
        super(wsdlLocation, PAYMENTSERVICEINTERNAL_QNAME);
    }

    public PaymentServiceInternal_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAYMENTSERVICEINTERNAL_QNAME, features);
    }

    public PaymentServiceInternal_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaymentServiceInternal_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PaymentServiceInternal
     */
    @WebEndpoint(name = "PaymentServiceInternalPort")
    public PaymentServiceInternal getPaymentServiceInternalPort() {
        return super.getPort(new QName("http://controller.financialWS.financial.services.web.suia.ambiente.gob.ec/", "PaymentServiceInternalPort"), PaymentServiceInternal.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaymentServiceInternal
     */
    @WebEndpoint(name = "PaymentServiceInternalPort")
    public PaymentServiceInternal getPaymentServiceInternalPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://controller.financialWS.financial.services.web.suia.ambiente.gob.ec/", "PaymentServiceInternalPort"), PaymentServiceInternal.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAYMENTSERVICEINTERNAL_EXCEPTION!= null) {
            throw PAYMENTSERVICEINTERNAL_EXCEPTION;
        }
        return PAYMENTSERVICEINTERNAL_WSDL_LOCATION;
    }

}
