
package ec.gob.consulta;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import ec.gob.ambiente.util.Constant;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
//@WebServiceClient(name = "ClienteCapasService", targetNamespace = "http://consulta.gob.ec/", wsdlLocation = "http://172.16.14.104:8180/ConsultaCapas/ClienteCapas?wsdl")
@WebServiceClient(name = "ClienteCapasService", targetNamespace = "http://consulta.gob.ec/")
public class ClienteCapasService
    extends Service
{

    private final static URL CLIENTECAPASSERVICE_WSDL_LOCATION;
    private final static WebServiceException CLIENTECAPASSERVICE_EXCEPTION;
    private final static QName CLIENTECAPASSERVICE_QNAME = new QName("http://consulta.gob.ec/", "ClienteCapasService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            //url = new URL("http://172.16.14.104:8180/ConsultaCapas/ClienteCapas?wsdl");
            url = new URL(Constant.getServiceClienteCapas());
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLIENTECAPASSERVICE_WSDL_LOCATION = url;
        CLIENTECAPASSERVICE_EXCEPTION = e;
    }

    public ClienteCapasService() {
        super(__getWsdlLocation(), CLIENTECAPASSERVICE_QNAME);
    }

    public ClienteCapasService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLIENTECAPASSERVICE_QNAME, features);
    }

    public ClienteCapasService(URL wsdlLocation) {
        super(wsdlLocation, CLIENTECAPASSERVICE_QNAME);
    }

    public ClienteCapasService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLIENTECAPASSERVICE_QNAME, features);
    }

    public ClienteCapasService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClienteCapasService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClienteCapas
     */
    @WebEndpoint(name = "ClienteCapasPort")
    public ClienteCapas getClienteCapasPort() {
        return super.getPort(new QName("http://consulta.gob.ec/", "ClienteCapasPort"), ClienteCapas.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClienteCapas
     */
    @WebEndpoint(name = "ClienteCapasPort")
    public ClienteCapas getClienteCapasPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://consulta.gob.ec/", "ClienteCapasPort"), ClienteCapas.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLIENTECAPASSERVICE_EXCEPTION!= null) {
            throw CLIENTECAPASSERVICE_EXCEPTION;
        }
        return CLIENTECAPASSERVICE_WSDL_LOCATION;
    }

}
